apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server
        ports:
        - containerPort: 50051

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer
spec:
  selector:
    matchLabels:
      app: peer
  replicas: 5
  template:
    metadata:
      labels:
        app: peer
    spec:
      containers:
      - name: peer
        image: peer
        ports:
        - containerPort: 50052
